apiVersion: app.stacks/v1beta1
kind: RuntimeComponent
metadata:
  name: tomcat
  labels:
    application: "demo"
spec:
  applicationName: tomcat
  applicationImage: tomcat-stream
  autoscaling:
    maxReplicas: 4
    targetCPUUtilizationPercentage: 30
  resourceConstraints:
    requests:
      cpu: 100m
  expose: true
  env:
    - name: KUBERNETES_NAMESPACE
      value: tomcat-cluster
